"""empty message

Revision ID: 4aff3c1223db
Revises: aa84944441d8
Create Date: 2024-11-07 17:20:52.766087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aff3c1223db'
down_revision = 'aa84944441d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.drop_index('ix_board_create_at')
        batch_op.create_index(batch_op.f('ix_board_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('updatw_at')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updatw_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_board_created_at'))
        batch_op.create_index('ix_board_create_at', ['create_at'], unique=False)
        batch_op.alter_column('user_name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
