"""empty message

Revision ID: c0ad9a1e72b6
Revises: f34be10b6922
Create Date: 2024-10-10 16:46:47.539385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ad9a1e72b6'
down_revision = 'f34be10b6922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updatw_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_auth_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auth_username'))
        batch_op.drop_index(batch_op.f('ix_users_auth_email'))

    op.drop_table('users_auth')
    # ### end Alembic commands ###
